schedule: "* * * * *"
archive_ttl: "10m"
paths_to_backup:
  - test/dir
  - test/test.txt
  - test/wildcard/*.txt
glacier:
  id: myamazonid
  secret: myamazonsecretsecret
  region: us-east-1
  vault_name: myglaciervaultname